# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-07 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='\u5546\u54c1\u6570\u91cf')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Product', verbose_name='\u5546\u54c1')),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(to='mall.ProductItem', verbose_name='\u5546\u54c1'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='products',
            field=models.ManyToManyField(to='mall.ProductItem', verbose_name='\u5546\u54c1'),
        ),
    ]
