# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-07 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20171107_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, null=True, to='mall.Product', verbose_name='\u76f8\u5173\u5546\u54c1'),
        ),
    ]
