# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-07 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_auto_20171107_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='user_phone',
            field=models.CharField(default='', max_length=11, verbose_name='\u624b\u673a\u53f7'),
        ),
    ]
