# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-08 02:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mall', '0004_auto_20171107_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_user', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='products',
            field=models.ManyToManyField(null=True, to='mall.ProductItem', verbose_name='\u5546\u54c1'),
        ),
    ]
