# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-08 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_auto_20171108_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='receiver_phone',
            field=models.CharField(default='', max_length=11, verbose_name='\u6536\u8d27\u624b\u673a\u53f7'),
        ),
    ]
