# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yipai', models.IntegerField()),
                ('yixin', models.IntegerField()),
                ('huimaiche', models.IntegerField()),
                ('yichehui', models.IntegerField()),
                ('ershouche', models.IntegerField()),
                ('week', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='communityposts',
            name='share_posts',
            field=models.IntegerField(default=0),
        ),
    ]
