# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0002_auto_20161019_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPostsApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_posts', models.IntegerField()),
                ('question_posts', models.IntegerField()),
                ('vote_posts', models.IntegerField()),
                ('bycar_posts', models.IntegerField()),
                ('share_posts', models.IntegerField()),
                ('week', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
