# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0003_communitypostsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlines',
            name='car_photo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='headlines',
            name='car_summary',
            field=models.IntegerField(default=0),
        ),
    ]
