# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0006_carconversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_add', models.IntegerField()),
                ('post_reply', models.IntegerField()),
                ('post_like', models.IntegerField()),
                ('post_add_app', models.IntegerField()),
                ('post_good', models.IntegerField()),
                ('post_add_uv', models.IntegerField()),
                ('post_home', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
