# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0007_postdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='post_type',
            field=models.IntegerField(default=99),
        ),
    ]
