# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0008_postdetail_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadlinesRealtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('item_key', models.CharField(max_length=20)),
                ('item_value', models.IntegerField()),
            ],
        ),
    ]
