# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0009_headlinesrealtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadlineDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('platform', models.CharField(max_length=10)),
                ('toutiao_article', models.IntegerField()),
                ('car_article', models.IntegerField()),
                ('toutiao_video', models.IntegerField()),
                ('car_video', models.IntegerField()),
                ('toutiao_photo', models.IntegerField()),
            ],
        ),
    ]
