# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0010_headlinedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('bn1', models.IntegerField()),
                ('bn2', models.IntegerField()),
                ('bn3', models.IntegerField()),
                ('bn4', models.IntegerField()),
                ('bn5', models.IntegerField()),
                ('bn6', models.IntegerField()),
                ('bn7', models.IntegerField()),
                ('bn8', models.IntegerField()),
                ('bn9', models.IntegerField()),
            ],
        ),
    ]
