# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-26 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0014_newsread'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=20)),
                ('news_add', models.IntegerField()),
                ('news_commment', models.IntegerField()),
                ('news_share', models.IntegerField()),
            ],
        ),
    ]
