# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-26 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0015_newsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='news_read',
            field=models.IntegerField(default=0),
        ),
    ]
