# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-22 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0017_auto_20161226_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='appactive',
            name='ipad_active',
            field=models.IntegerField(default=0),
        ),
    ]
