# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-22 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0018_appactive_ipad_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleuser',
            name='my_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moduleuser',
            name='target',
            field=models.CharField(default='uv', max_length=20),
        ),
    ]
