# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-22 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0019_auto_20170222_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='appadd',
            name='ipad_add',
            field=models.IntegerField(default=0),
        ),
    ]
