# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0020_appadd_ipad_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('channel', models.CharField(max_length=20)),
                ('install', models.IntegerField()),
                ('active_user', models.IntegerField()),
                ('platform', models.CharField(max_length=10)),
            ],
        ),
    ]
