# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-15 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0021_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('headline', models.IntegerField()),
                ('community', models.IntegerField()),
                ('car', models.IntegerField()),
                ('service', models.IntegerField()),
                ('my', models.IntegerField()),
                ('app_daily', models.IntegerField()),
                ('app_single', models.IntegerField()),
                ('adr', models.IntegerField()),
                ('ios', models.IntegerField()),
            ],
        ),
    ]
