# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-21 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0022_appstay'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('active', models.IntegerField()),
                ('login', models.IntegerField()),
                ('headline', models.IntegerField()),
                ('community', models.IntegerField()),
                ('car', models.IntegerField()),
                ('service', models.IntegerField()),
                ('my', models.IntegerField()),
            ],
        ),
    ]
