# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-21 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0023_appcore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('news_all', models.IntegerField()),
                ('news', models.IntegerField()),
                ('media', models.IntegerField()),
                ('album', models.IntegerField()),
                ('video', models.IntegerField()),
                ('live', models.IntegerField()),
                ('videoplay', models.IntegerField()),
                ('post', models.IntegerField()),
                ('carmodel', models.IntegerField()),
            ],
        ),
    ]
