# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-23 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0024_apppageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcore',
            name='newadd',
            field=models.IntegerField(default=0),
        ),
    ]
