# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0025_appcore_newadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstay',
            name='adr_daily',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appstay',
            name='ios_daily',
            field=models.IntegerField(default=0),
        ),
    ]
