# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-06 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0026_auto_20170628_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('askprice', models.IntegerField()),
                ('askpriceok', models.IntegerField()),
                ('loan', models.IntegerField()),
                ('loan_ok', models.IntegerField()),
                ('buynewcar', models.IntegerField()),
                ('buycar_ok', models.IntegerField()),
                ('replace', models.IntegerField()),
                ('replace_ok', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('phone_call', models.IntegerField()),
            ],
        ),
    ]
