# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-11 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0028_appkeyvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypostsapp',
            name='koubei_posts',
            field=models.IntegerField(default=0),
        ),
    ]
