# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-13 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0029_communitypostsapp_koubei_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkeyvalue',
            name='c_type',
            field=models.CharField(default='uv', max_length=20),
        ),
    ]
