# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-18 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0030_appkeyvalue_c_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_key', models.CharField(max_length=20)),
                ('c_desc', models.CharField(max_length=40)),
            ],
        ),
    ]
