# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-19 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0032_postdetail_post_reply_uv'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkey',
            name='c_desc_en',
            field=models.CharField(default='NULL', max_length=40),
        ),
    ]
