# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-19 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0033_appkey_c_desc_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appkey',
            name='c_desc_en',
        ),
    ]
