# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-26 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0034_remove_appkey_c_desc_en'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppCore',
        ),
        migrations.DeleteModel(
            name='AppPageView',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
