# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-26 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0036_appbasic'),
    ]

    operations = [
        migrations.AddField(
            model_name='appbasic',
            name='month',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appbasic',
            name='week',
            field=models.CharField(default='', max_length=20),
        ),
    ]
