# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-26 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0038_auto_20170726_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppActive',
        ),
        migrations.DeleteModel(
            name='AppAdd',
        ),
        migrations.DeleteModel(
            name='AppStarts',
        ),
    ]
