# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-28 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0040_appindex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppBasic',
        ),
        migrations.DeleteModel(
            name='AppData',
        ),
        migrations.DeleteModel(
            name='AppLogin',
        ),
        migrations.DeleteModel(
            name='AppPosts',
        ),
        migrations.DeleteModel(
            name='AppRetain',
        ),
        migrations.DeleteModel(
            name='AppStay',
        ),
        migrations.DeleteModel(
            name='AppVideo',
        ),
        migrations.DeleteModel(
            name='CarBusiness',
        ),
        migrations.DeleteModel(
            name='CarButton',
        ),
        migrations.DeleteModel(
            name='CommunityConversion',
        ),
        migrations.DeleteModel(
            name='CommunityHome',
        ),
        migrations.DeleteModel(
            name='CommunityPosts',
        ),
        migrations.DeleteModel(
            name='CommunityPostsApp',
        ),
        migrations.DeleteModel(
            name='CommunityRealtime',
        ),
        migrations.DeleteModel(
            name='HeadlineDetail',
        ),
        migrations.DeleteModel(
            name='HeadLines',
        ),
        migrations.DeleteModel(
            name='HeadLinesButton',
        ),
        migrations.DeleteModel(
            name='HeadLinesEffect',
        ),
        migrations.DeleteModel(
            name='HeadLinesFocus',
        ),
        migrations.DeleteModel(
            name='HeadLinesIcon',
        ),
        migrations.DeleteModel(
            name='HeadlinesRealtime',
        ),
        migrations.DeleteModel(
            name='HeadLinesSection',
        ),
        migrations.DeleteModel(
            name='ModuleUser',
        ),
        migrations.DeleteModel(
            name='NewsData',
        ),
        migrations.DeleteModel(
            name='NewsRead',
        ),
        migrations.DeleteModel(
            name='PostDetail',
        ),
    ]
