# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-09 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0041_auto_20170728_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField()),
                ('c_key', models.CharField(max_length=40)),
                ('c_uv', models.IntegerField()),
                ('c_pv', models.IntegerField()),
            ],
        ),
    ]
