# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-11 02:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('push', '0042_appcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDaily',
            fields=[
                ('daily_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('daily_desc', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DailyToEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_emails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('daily_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push.AppDaily')),
            ],
        ),
    ]
