# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-11 02:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('push', '0043_appdaily_dailytoemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytoemail',
            name='daily_emails',
        ),
        migrations.RemoveField(
            model_name='dailytoemail',
            name='daily_name',
        ),
        migrations.AddField(
            model_name='appdaily',
            name='daily_emails',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DailyToEmail',
        ),
    ]
