# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-17 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import push.models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0044_auto_20170811_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_desc', models.CharField(max_length=40)),
                ('chart_model', models.CharField(max_length=20)),
                ('chart_key', models.CharField(max_length=20, null=True)),
                ('chart_list', push.models.ListField()),
                ('chart_url', models.CharField(max_length=20)),
            ],
        ),
    ]
