# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-18 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import push.models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0046_auto_20170818_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appchart',
            name='chart_model',
        ),
        migrations.RemoveField(
            model_name='appchart',
            name='chart_url',
        ),
        migrations.AddField(
            model_name='appchart',
            name='chart_list_cn',
            field=push.models.ListField(default=''),
        ),
        migrations.AlterField(
            model_name='appchart',
            name='chart_key',
            field=models.CharField(default='', max_length=20),
        ),
    ]
