# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-18 09:50
from __future__ import unicode_literals

from django.db import migrations
import push.models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0047_auto_20170818_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appchart',
            name='chart_list',
            field=push.models.JSONField(),
        ),
        migrations.AlterField(
            model_name='appchart',
            name='chart_list_cn',
            field=push.models.JSONField(default=''),
        ),
    ]
