# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-21 07:21
from __future__ import unicode_literals

from django.db import migrations
import push.models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0048_auto_20170818_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appchart',
            name='chart_list',
            field=push.models.ListField(),
        ),
        migrations.AlterField(
            model_name='appchart',
            name='chart_list_cn',
            field=push.models.ListField(default=''),
        ),
    ]
