# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-24 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0049_auto_20170821_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('app_active', ''), ('app_add', ''), ('app_retain', ''), ('app_starts', ''), ('app_channel', ''), ('moduleuser', ''), ('app_stay', ''), ('app_core', ''), ('app_core2', ''), ('business', ''), ('app_business', ''), ('app_video', ''), ('app_media', ''), ('news_data', ''), ('posts_app', ''), ('post_detail', ''), ('car_coin', '')),
            },
        ),
    ]
