# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-24 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0052_auto_20170824_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomAccess',
            new_name='Access',
        ),
    ]
