# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-27 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0056_objectset_pageset_typeset_viewset'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40)),
                ('type_desc', models.CharField(max_length=40)),
                ('type_name', models.CharField(max_length=40)),
                ('page_name', models.CharField(max_length=40)),
                ('column_name', models.CharField(blank=True, max_length=20)),
                ('section_name', models.CharField(blank=True, max_length=20)),
                ('view_name', models.CharField(max_length=20)),
                ('object_name', models.CharField(blank=True, max_length=20)),
                ('object_id', models.IntegerField(blank=True, max_length=20)),
            ],
        ),
    ]
