# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-27 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('push', '0057_loglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='loglist',
            name='user_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loglist',
            name='object_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='loglist',
            name='page_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push.PageSet'),
        ),
        migrations.AlterField(
            model_name='loglist',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push.TypeSet'),
        ),
        migrations.AlterField(
            model_name='loglist',
            name='view_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push.ViewSet'),
        ),
    ]
