# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-27 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0058_auto_20170927_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglist',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
