# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-29 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0060_auto_20170928_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglist',
            name='column_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u680f\u76ee'),
        ),
        migrations.AlterField(
            model_name='loglist',
            name='section_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6bb5\u843d'),
        ),
    ]
