# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-29 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0061_auto_20170929_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeset',
            name='type_name',
            field=models.CharField(max_length=30),
        ),
    ]
