# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-29 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0062_auto_20170929_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageset',
            name='module_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='typeset',
            name='type_desc',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='typeset',
            name='type_name',
            field=models.CharField(max_length=40),
        ),
    ]
