# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-29 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0066_appversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglist',
            name='user_name',
            field=models.ForeignKey(help_text='\u5fc5\u9700*', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u540d'),
        ),
        migrations.AlterField(
            model_name='loglist',
            name='version',
            field=models.ForeignKey(help_text='\u5fc5\u9700*', on_delete=django.db.models.deletion.CASCADE, to='push.AppVersion', verbose_name='\u7248\u672c\u53f7'),
        ),
    ]
