# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-30 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0068_auto_20170930_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageset',
            options={'ordering': ['-page_desc']},
        ),
        migrations.AddField(
            model_name='loglist',
            name='object_type',
            field=models.ForeignKey(default=14, help_text='\u5bf9\u8c61\u7c7b\u578b\uff0c\u5fc5\u9700*', on_delete=django.db.models.deletion.CASCADE, to='push.ObjectSet', verbose_name='\u5bf9\u8c61'),
        ),
    ]
