# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-12 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0069_auto_20170930_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='loglist',
            name='source',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6765\u6e90'),
        ),
    ]
