# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-16 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0070_loglist_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglist',
            name='object_name',
            field=models.CharField(blank=True, help_text='\u82e5\u5bf9\u8c61\u4e3a\u5176\u4ed6,\u5219Name\u4e0d\u53ef\u4e3a\u7a7a*', max_length=20, null=True, verbose_name='name'),
        ),
    ]
