# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-31 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import push.models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0071_auto_20171016_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppOperate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField()),
                ('c_key', models.CharField(max_length=30)),
                ('c_value', push.models.JSONField()),
            ],
        ),
    ]
