from django.shortcuts import render
from django.conf.urls import url
from push import views as push_views
from push import mails as push_mails
from django.conf import settings
from django.conf.urls.static import static
from push.views import UserCreate,UserUpdate,UserDelete,UserListList,UserListDetail

urlpatterns = [
	url(r'^push_open/', push_views.push_open,name='home'),
	url(r'^after_open/', push_views.after_open,name='home'),
	url(r'^push_click/', push_views.push_click,name='home'),
	url(r'^push_active/', push_views.push_active,name='home'),
	url(r'^area_active/', push_views.area_active,name='home'),
	url(r'^push_content/', push_views.push_content,name='home'),
	url(r'^loss_active/', push_views.loss_active,name='home'),
	url(r'^push_login/', push_views.push_login,name='home'),
	url(r'^app_active/', push_views.app_active,name='home'),
	url(r'^app_add/', push_views.app_add,name='home'),
	url(r'^app_channel/', push_views.app_channel,name='home'),
	url(r'^app_video/', push_views.app_video,name='home'),
	url(r'^app_starts/', push_views.app_starts,name='home'),
	url(r'^app_retain/', push_views.app_retain,name='home'),
	url(r'^app_stay/',push_views.app_stay,name='app_stay'),
	url(r'^app_stays/',push_views.app_stay,name='app_stay'),
	url(r'^app_core/',push_views.app_core,name='app_core'),
	url(r'^app_core2/',push_views.app_core2,name='app_core2'),
	url(r'^business/',push_views.business,name='business'),
	url(r'^app_media/', push_views.app_media,name='home'),
	url(r'^car_coin/', push_views.car_coin,name='home'),
	url(r'^moduleuser/', push_views.moduleuser,name='home'),
	url(r'^app_business/', push_views.app_business,name='home'),
	url(r'^posts_app/', push_views.posts_app,name='home'),
	url(r'^logout_view/', push_views.logout_view,name='home'),
	url(r'^push_send/', push_views.push_send,name='home'),
	url(r'^news_data/',push_views.news_data,name='home'),
	url(r'^post_detail/',push_views.post_detail,name='home'),
	url(r'^register/',push_views.register,name='home'),
	url(r'^forget_password/',push_views.forget_password,name='home'),
	url(r'^reset_password/(?P<encrypt>(.*?))/$',push_views.reset_password,name='home'),
	url(r'^car_conversion/', push_views.car_conversion,name='home'),
	url(r'^news_real/',push_views.news_real,name='home'),
	url(r'^news_real2/(\w+)/(\d+)/$', push_views.news_real2,name='news_real2'),
	url(r'^news_detail/',push_views.news_detail,name='news_detail'),
	url(r'^posts_real/',push_views.posts_real,name='home'),
	url(r'^loglist_create/',push_views.loglist_create,name='loglist_create'),
	url(r'^posts_real2/(\w+)/(\d+)/$',push_views.posts_real2,name='home'),
	url(r'^car_daily/(?P<dt>(.*?))/$',push_mails.car_daily,name='car_daily'),
	url(r'^headline_daily/(?P<dt>(.*?))/$',push_mails.headline_daily,name='headline_daily'),
	url(r'^log_export/(.*?)/$',push_mails.log_export,name='log_export'),
	url(r'^app_tem/(?P<chart_key>(.*?))/$',push_views.app_tem,name='app_tem'),
	url(r'^daily_start/$',push_mails.daily_start,name='daily_start'),
	url(r'^userlist/add/$', UserCreate.as_view(), name='user_create'),
	url(r'^userlist/(?P<pk>[0-9]+)/update/$', UserUpdate.as_view(), name='user_update'),
	url(r'^userlist/(?P<pk>[0-9]+)/delete/$', UserDelete.as_view(), name='user_delete'),
	url(r'^userlist/$', UserListList.as_view(),name='userlist'),
	url(r'^userlist/(?P<pk>[0-9]+)/$', UserListDetail.as_view(),name='userdetail'),
	url(r'^app_operate/$',push_views.app_operate,name='app_operate'),
	url(r'^app_modules/$',push_views.app_modules,name='app_modules'),
	]
