# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-19 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_name', to=settings.AUTH_USER_MODEL, verbose_name='\u76f4\u63a5\u9886\u5bfc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u540d')),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(max_length=20, verbose_name='\u6d41\u540d\u79f0')),
                ('c_dt', models.DateTimeField(auto_now=True, verbose_name='\u89e6\u53d1\u65f6\u95f4')),
                ('remark', models.CharField(max_length=20, null=True, verbose_name='\u53d1\u8d77\u5185\u5bb9')),
                ('state', models.CharField(max_length=20, verbose_name='\u6d41\u72b6\u6001')),
                ('executor', models.CharField(max_length=20, verbose_name='\u987a\u4f4d\u5ba1\u6279\u4eba')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_name', to='flow.Employee', verbose_name='\u53d1\u8d77\u4eba')),
            ],
        ),
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_dt', models.DateTimeField(auto_now=True, verbose_name='\u89e6\u53d1\u65f6\u95f4')),
                ('operate', models.CharField(max_length=20, verbose_name='\u64cd\u4f5c')),
                ('remark', models.CharField(max_length=20, null=True, verbose_name='\u5907\u6ce8\u5185\u5bb9')),
                ('executor', models.CharField(max_length=20, verbose_name='\u987a\u4f4d\u5ba1\u6279\u4eba')),
                ('flowid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Flow', verbose_name='\u5de5\u4f5c\u6d41ID')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator', to='flow.Employee', verbose_name='\u64cd\u4f5c\u8005')),
            ],
            options={
                'ordering': ['c_dt'],
            },
        ),
    ]
