# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-23 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20171019_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='remark',
            field=models.TextField(max_length=20, null=True, verbose_name='\u53d1\u8d77\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='flownode',
            name='remark',
            field=models.TextField(max_length=20, null=True, verbose_name='\u5907\u6ce8\u5185\u5bb9'),
        ),
    ]
