# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-25 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0006_auto_20171024_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='progress',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u8fdb\u5ea6'),
        ),
    ]
