# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-26 01:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flow', '0007_flow_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='executor_group',
            field=models.ManyToManyField(null=True, related_name='executor_group', to=settings.AUTH_USER_MODEL, verbose_name='\u987a\u4f4d\u6267\u884c\u7ec4'),
        ),
    ]
