# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-26 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0008_flow_executor_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='title',
            field=models.CharField(default='', max_length=40, verbose_name='\u6807\u9898'),
        ),
    ]
