# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-26 05:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flow', '0009_flow_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='operator_group',
            field=models.ManyToManyField(null=True, related_name='operator_group', to=settings.AUTH_USER_MODEL, verbose_name='\u7ecf\u624b\u4eba'),
        ),
    ]
